import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        div {
  margin: 10px;
  padding: 10px;
}

.foaie {
  background: repeating-linear-gradient(
    0deg,
    #ccc576,
    #ccc576 20px,
    rgba(0, 0, 0, 0.2) 20px,
    rgb(255 251 210) 21px
  );
}

.lista > input {
  text-align: center;
  text-decoration: underline;
  font-family: 'Gochi Hand', cursive;
}

.magazin > input[type="text"] {
  font-size: 200%;
  text-decoration: underline;
  font-family: 'Sacramento', cursive;
}

input:not([type="checkbox"]):not([value="adauga"]):not(.form-control):not([value="adauga magazin nou"]) {
  background-color: transparent;
  border: 0;
}

.produs > input[type="text"] {
  font-style: italic;
  font-family: 'Gochi Hand', cursive;
}

.produs > input[type="number"] {
  width: 35px;
  font-family: 'Sacramento', cursive;
}

.lista > input {
  width: 100%;
}

input[type="text"] {
  font-family: 'Gochi Hand', cursive;
}

.form-select {
  width: 70px;
  display: inline-block;
}
.bg-success {
  --bs-bg-opacity: 1;
  width: 30%
  }
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
